### ISSUE TITLE
Useless SyntaxError Message

### ISSUE THREAD

**Issue by joshrhoades** [TrySound/rollup-plugin-uglify#11]
I've been banging my head for hours trying to track down this error, trolling through other issues in this repo (and uglify, and grunt-uglify, etc. etc.) that are similar to the point of even reporting virtually identical errors, but nothing discussed or addressed in any of those has helped. I've even gone so far as injected additional logging into rollup.js itself to get a more specific error log, but no joy.

When running rollup in production mode (uglify running with the harmony branch for es6), I get an uglify error that is absolutely useless:

```
Error transforming bundle with 'uglify' plugin: SyntaxError: Unexpected character '`'
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at parse_error (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1677:9)
    at Object.next_token [as input] (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1949:9)
    at next (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2078:25)
    at subscripts (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2774:13)
    at expr_atom (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2631:20)
    at maybe_unary (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)
    at expr_ops (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2830:24)
    at maybe_conditional (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2835:20)
    at maybe_assign (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2859:20)
    at expression (eval at <anonymous> (/Users/me/Development/projectX/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2878:20)
```

I am using es6 templates, so there are valid backticks, I also have them in jsDocs for code formatting, so there are numerous places to check to find something...or I could actually get a useful error message that gives me a proper file.

I've also tried to find as much as I could about running rollup with some kind of debug mode, but nothing in that vein has born fruit either.

Take uglify out of the mix, no problem, its clearly related to the minification, but it just isn't helpful at tracking down the cause. I am using the `rollup-plugin-uglify`, but using the harmony branch from `uglify-js` for the minification itself, so my `uglify` config is thus (`rollup.config.js`):
```javascript
import buble from 'rollup-plugin-buble';
import uglify from 'rollup-plugin-uglify';
import {minify} from 'uglify-js';
...
export default {
    ...,
    plugins: [
        uglify({}, minify)
    ]
}
```

At this point it may just be faster to just start excluding parts of my bundle until I hit on it, but I also want to be able to debug this more easily in the future as that is always the ideal.

What am I missing?

* npm 3.10.8
* node 5.6.0
* Rollup 0.36.0
* rollup-plugin-buble 0.14.0
* uglify-js (for `minify`) 2.7.3
* rollup-plugin-uglify 1.0.1

Thanks.

**Comment by TrySound** [comment]
@joshrhoades Hi! I don't think I can help you with it. I just report what uglify itself throws me. You can move this issue there.
