### ISSUE TITLE
"preserveComments" causes error

### ISSUE THREAD

**Issue by yairEO** [TrySound/rollup-plugin-uglify#23]
When using `uglify` without the rollup plugin, it works well with the [preserveComments](https://github.com/terinjokes/gulp-uglify#options) option, but when passing that setting to the `rollup-plugin-uglify` I do see an error:

````
TypeError: Cannot set property 'comments' of null                                       
    at setup (C:\www\UI\BUILD\node_modules\gulp-uglify\minifier.js:44:29)               
    at DestroyableTransform.minify [as _transform] (C:\www\UI\BUILD\node_modules\gulp-ug
lify\minifier.js:54:19)                                                                 
    at DestroyableTransform.Transform._read (C:\www\UI\BUILD\node_modules\through2\node_
modules\readable-stream\lib\_stream_transform.js:159:10)                                
    at DestroyableTransform.Transform._write (C:\www\UI\BUILD\node_modules\through2\node
_modules\readable-stream\lib\_stream_transform.js:147:83)                               
    at doWrite (C:\www\UI\BUILD\node_modules\through2\node_modules\readable-stream\lib\_
stream_writable.js:347:64)                                                              
    at writeOrBuffer (C:\www\UI\BUILD\node_modules\through2\node_modules\readable-stream
\lib\_stream_writable.js:336:5)                                                         
    at DestroyableTransform.Writable.write (C:\www\UI\BUILD\node_modules\through2\node_m
odules\readable-stream\lib\_stream_writable.js:274:11)                                  
    at write (C:\www\UI\BUILD\node_modules\vinyl-fs\node_modules\readable-stream\lib\_st
ream_readable.js:623:24)                                                                
    at flow (C:\www\UI\BUILD\node_modules\vinyl-fs\node_modules\readable-stream\lib\_str
eam_readable.js:632:7)                                                                  
    at DestroyableTransform.pipeOnReadable (C:\www\UI\BUILD\node_modules\vinyl-fs\node_m
odules\readable-stream\lib\_stream_readable.js:664:5)                                   
    at emitNone (events.js:86:13)                                                       
    at DestroyableTransform.emit (events.js:185:7)                                      
    at emitReadable_ (C:\www\UI\BUILD\node_modules\vinyl-fs\node_modules\readable-stream
\lib\_stream_readable.js:448:10)                                                        
    at emitReadable (C:\www\UI\BUILD\node_modules\vinyl-fs\node_modules\readable-stream\
lib\_stream_readable.js:444:5)                                                          
    at readableAddChunk (C:\www\UI\BUILD\node_modules\vinyl-fs\node_modules\readable-str
eam\lib\_stream_readable.js:187:9)                                                      
    at DestroyableTransform.Readable.push (C:\www\UI\BUILD\node_modules\vinyl-fs\node_mo
dules\readable-stream\lib\_stream_readable.js:149:10)    
````                               

## uglify configuration:

````
{
    compress: {
        drop_debugger : true,
        sequences     : true,
        conditionals  : true,
        booleans      : true,
        unused        : true,
        if_return     : true,
        join_vars     : true,
        properties    : true,
        dead_code     : true
    },
    mangle           : true,
    "screw-ie8"      : true,
    preserveComments : 'license'   //   <--------
}
````

**Comment by TrySound** [comment]
gulp-uglify introduced a few own defaults around uglify.
https://github.com/terinjokes/gulp-uglify/blob/master/minifier.js#L38

**Comment by yairEO** [comment]
why don't they say so in their README :/ 
I will write them to **specifically** divide the default options and their own specially added ones.

Thanks Bogdan!
