### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by matt3224** [TrySound/rollup-plugin-uglify#31]
Hey,

I updated to 2.0.0 and updated the reference to uglify-es in my rollup config, but i get the following error and have had to downgrade to bundle successfully. Is there something else i need to do?

`Cannot read property 'length' of undefined`

Here's my rollup config:
```js
// Rollup plugins
import eslint from 'rollup-plugin-eslint';
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-es';

export default {
    entry : './scripts/application/application.js',
    dest : './scripts/application/application.min.js',
    format : 'iife',
    plugins: [
        eslint({
            "env": {
                "browser": true,
                "es6": true
            },
            "extends": "eslint:recommended",
            "parserOptions": {
                "sourceType": "module"
            },
            "rules": {
                "linebreak-style": [
                    "error",
                    "unix"
                ],
                "semi": [
                    "warn",
                    "always"
                ],
                "no-unused-vars": "off",
                "no-undef": "off",
                "no-console": "off"
            }
        }),
        babel({
            exclude : ['./node_modules/**', './scripts/parties/**'],
            presets : [[
                "env", {
                    "targets" : {
                        "browsers" : ["> 1%", "last 2 versions", "Firefox ESR", "not ie_mob <= 12"]
                    },
                    "modules" : false
                }
            ]],
            plugins : [
                "external-helpers"
            ]
        }),
        uglify({
            screwIE8 : true
        }, minify)
    ]
};
```

Also here's my package json:
```json
{
  "name": "project",
  "version": "1.0.0",
  "author": "Team",
  "devDependencies": {
    "autoprefixer": "^7.1.1",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-env": "^1.4.0",
    "browser-sync": "^2.18.11",
    "node-sass": "^4.5.3",
    "onchange": "^3.2.1",
    "parallelshell": "^2.0.0",
    "postcss-cli": "^4.0.0",
    "rollup": "^0.41.6",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-eslint": "^3.0.0",
    "rollup-plugin-uglify": "^2.0.0",
    "rollup-watch": "^3.2.2",
    "stylelint": "^7.10.1",
    "uglify-es": "^3.0.9"
  },
  "stylelint": {
    "rules": {
      "indentation": 4,
      "number-leading-zero": null
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "Firefox ESR",
    "iOS 9",
    "not ie_mob <= 12",
    "not ie <= 10",
    "not blackberry <= 7"
  ],
  "scripts": {
    "lint-scss": "stylelint ./styles/**/*.scss --cache --syntax scss",
    "scss": "node-sass --omit-source-map-url --recursive --output-style compressed --output ./styles ./styles",
    "autoprefixer": "postcss --use autoprefixer --replace ./styles/style.css --no-map",
    "build:css": "yarn run lint-scss --silent | yarn run scss --silent | yarn run autoprefixer --silent",
    "build:js": "rollup --config",
    "serve": "browser-sync start --https --no-notify --proxy 'right.lance' --files './styles/**/*.css, ./views/**/*.php, ./**/*.html, !node_modules/**/*.html'",
    "watch:css": "onchange './styles/**/*.scss' -- yarn run build:css --silent",
    "watch:js": "rollup --config --watch",
    "watch:all": "parallelshell 'yarn run serve --silent' 'yarn run watch:css --silent' 'yarn run watch:js --silent'",
    "postinstall": "yarn run watch:all --silent",
    "go": "yarn run postinstall --silent"
  }
}
```

Thanks!

**Comment by TrySound** [comment]
@matt3224 Can you post full stacktrace of error?

**Comment by matt3224** [comment]
Here's what i get in full in terminal and the log that npm makes

```
🚨   Cannot read property 'length' of undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rightlance@1.0.0 build:js: `rollup --config`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rightlance@1.0.0 build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Matt/.npm/_logs/2017-05-20T19_34_31_280Z-debug.log
Matts-iMac:RightLance Matt$
```
[2017-05-20T19_34_31_280Z-debug.txt](https://github.com/TrySound/rollup-plugin-uglify/files/1016452/2017-05-20T19_34_31_280Z-debug.txt)

**Comment by TrySound** [comment]
@matt3224 Looks like it's a bug in uglify-es.

**Comment by TrySound** [comment]
Try to pass `sourceMap: false`

**Comment by matt3224** [comment]
No luck i'm afraid, here's the updated log if you need. Not sure what else i can try, seems odd for it to just completely fail like that eh
[2017-05-21T17_28_51_673Z-debug.txt](https://github.com/TrySound/rollup-plugin-uglify/files/1017189/2017-05-21T17_28_51_673Z-debug.txt)

**Comment by TrySound** [comment]
Try to do the same but with rollup API and catch error in promise to see real stacktrace.

**Comment by matt3224** [comment]
Ok, I think this is correct...

```js
var rollup = require('rollup');
var eslint = require('rollup-plugin-eslint');
var babel = require('rollup-plugin-babel');
var uglify = require('rollup-plugin-uglify');
var minify = require('uglify-es').minify;
var stderr = console.error.bind(console);
rollup.rollup({
    entry: './scripts/application/application.js',
    plugins: [
        eslint({
            "env": {
                "browser": true,
                "es6": true
            },
            "extends": "eslint:recommended",
            "parserOptions": {
                "sourceType": "module"
            },
            "rules": {
                "linebreak-style": [
                    "error",
                    "unix"
                ],
                "semi": [
                    "warn",
                    "always"
                ],
                "no-unused-vars": "off",
                "no-undef": "off",
                "no-console": "off"
            }
        }),
        babel({
            exclude : ['./node_modules/**', './scripts/parties/**'],
            presets : [[
                "env", {
                    "targets" : {
                        "browsers" : ["> 1%", "last 2 versions", "Firefox ESR", "not ie_mob <= 12"]
                    },
                    "modules" : false
                }
            ]],
            plugins : [
                "external-helpers"
            ]
        }),
        uglify({
            screwIE8 : true,
            sourceMap: false
        }, minify)
    ]
}).then( function ( bundle ) {
    try {
        bundle.write({
            format: 'iife',
            dest: './scripts/application/application2.min.js'
        });
    } catch(e) {
        stderr(e);
    }
});
```

..and here is the output:
```
TypeError: Cannot read property 'length' of undefined
    at Bundle$$1.render (/Users/Matt/Sites/RightLance/node_modules/rollup/dist/rollup.js:9734:17)
    at generate (/Users/Matt/Sites/RightLance/node_modules/rollup/dist/rollup.js:9915:26)
    at Object.write (/Users/Matt/Sites/RightLance/node_modules/rollup/dist/rollup.js:9947:18)
    at /Users/Matt/Sites/RightLance/rollup.build.js:54:16
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

Let me know if I need to make any changes, thanks

**Comment by TrySound** [comment]
@matt3224 That's better. Thanks. Try again with 2.0.1

**Comment by matt3224** [comment]
@TrySound excellent, all working now! Thanks
