### ISSUE TITLE
Error: Farm is ended, no more calls can be done to it

### ISSUE THREAD

**Issue by mengdu** [TrySound/rollup-plugin-uglify#56]
rollup.config.js
```js
const resolve = require('rollup-plugin-node-resolve')
const commonjs = require('rollup-plugin-commonjs')
const Eslint = require('rollup-plugin-eslint')
const babel = require('rollup-plugin-babel')
const Uglify = require('rollup-plugin-uglify')
const pkg = require('./package.json')

const banner =
  '/*!\n' +
  ' * Build version v' + pkg.version + '\n'  +
  ' */'

const isProduction = process.env.NODE_ENV === 'production'

module.exports = {
  input: 'src/index.js',
  output: [
    {
      // window.Marquee
      name: 'Marquee',
      file: isProduction ? 'dist/index.min.js' : 'dist/index.js',
      format: 'umd',
      banner: banner,
      sourcemap: false
    },
    { file: 'dist/index.cjs.js', format: 'cjs', banner: banner },
    { file: 'dist/index.esm.js', format: 'esm', banner: banner },
    { file: 'dist/index.amd.js', format: 'amd', banner: banner },
    { file: 'dist/index.iife.js', format: 'iife', name: 'Marquee', banner: banner }
  ],
  plugins: [
    Eslint.eslint({
      exclude: ['node_modules/**']
    }),
    resolve(),
    commonjs(),
    babel({
      exclude: 'node_modules/**'
    }),
    (isProduction && Uglify.uglify())
  ]
}
```
Error:
```ls
> rollup -c --environment NODE_ENV:production


src/index.js → dist/index.min.js, dist/index.cjs.js, dist/index.esm.js, dist/index.amd.js, dist/index.iife.js...
[!] (uglify plugin) Error: Farm is ended, no more calls can be done to it
Error: Farm is ended, no more calls can be done to it
    at exports.default.end (D:\work\marqueejs\node_modules\jest-worker\build\index.js:166:13)
    at Object.generateBundle (D:\work\marqueejs\node_modules\rollup-plugin-uglify\index.js:38:19)
    at D:\work\marqueejs\node_modules\rollup\dist\rollup.js:21962:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by TrySound** [comment]
Could you copy solution from terser plugin and make PR?
