### ISSUE TITLE
TypeError: rollupPluginUglify.uglify is not a function

### ISSUE THREAD

**Issue by utkarsh2102** [TrySound/rollup-plugin-uglify#80]
While building, I get the following error:

```
[!] TypeError: rollupPluginUglify.uglify is not a function
TypeError: rollupPluginUglify.uglify is not a function
    at Object.<anonymous> (/root/timeago/node-timeago.js/rollup.config.js:25:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.require.extensions..js (/usr/share/nodejs/rollup/bin/src/run/loadConfigFile.js:39:24)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/share/nodejs/rollup/bin/src/run/loadConfigFile.js:46:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by TrySound** [comment]
show your rollup config and which node version do you use?

**Comment by jamigibbs** [comment]
@utkarsh2102 You have to import the function like this: 

`import { uglify } from 'rollup-plugin-uglify'`
